<?php

declare(strict_types=1);

// Issue #776: False positive for backed properties implementing interface hooks
// https://github.com/carthage-software/mago/issues/776

interface TestInterface
{
    public int $backed { get; set; }

    public int $modified { get; }
}

// This class should NOT report any errors except missing-constructor for backed property:
// 1. $backed only defines set hook, but PHP auto-generates get for backed properties
// 2. $modified is a normal property with asymmetric visibility
// @mago-expect analysis:missing-constructor
final class Test implements TestInterface
{
    public int $backed {
        set(int $backed) {
            $this->backed = $backed;
            $this->modified = $backed + 1000;
        }
    }

    // Using default value since property initialization in hooks is runtime behavior
    public private(set) int $modified = 0;
}

// Additional test cases for backed vs virtual properties

interface GetterInterface
{
    public string $name { get; }
}

// Backed property with only get hook should satisfy interface
// @mago-expect analysis:missing-constructor
class BackedGetter implements GetterInterface
{
    public string $name {
        get => $this->name;  // Uses backing store - get is auto-generated by PHP
    }
}

// Normal property should satisfy interface with get hook
class NormalProperty implements GetterInterface
{
    public string $name = 'default';  // Normal backed property
}

interface SetterInterface
{
    public int $value { set; }
}

// Backed property with only set hook should satisfy interface
// @mago-expect analysis:missing-constructor
class BackedSetter implements SetterInterface
{
    public int $value {
        set(int $v) {
            $this->value = $v;  // Uses backing store
        }
    }
}
