//! Preset configurations for formatter settings.
//!
//! This module provides predefined formatter configurations that can be used to quickly
//! set up formatter settings with common coding standards.

use std::fmt;
use std::str::FromStr;

use schemars::JsonSchema;
use serde::Deserialize;
use serde::Serialize;

use crate::settings::*;

/// Available formatter presets.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "kebab-case", try_from = "String")]
pub enum FormatterPreset {
    /// Default preset (PER-CS compatible).
    #[default]
    Default,
    /// PSR-12 preset.
    Psr12,
    /// Pint preset (Laravel Pint compatible).
    Pint,
    /// Tempest preset (Tempest framework compatible).
    Tempest,
    /// Hack preset (`hackfmt` compatible).
    Hack,
    /// Drupal preset.
    Drupal,
}

impl FormatterPreset {
    /// Returns the `FormatSettings` for this preset.
    #[must_use]
    pub const fn settings(self) -> FormatSettings {
        match self {
            Self::Default => DEFAULT_PRESET,
            Self::Psr12 => PSR12_PRESET,
            Self::Pint => PINT_PRESET,
            Self::Tempest => TEMPEST_PRESET,
            Self::Hack => HACK_PRESET,
            Self::Drupal => DRUPAL_PRESET,
        }
    }

    /// Returns the canonical name of this preset.
    #[must_use]
    pub const fn name(self) -> &'static str {
        match self {
            Self::Default => "default",
            Self::Psr12 => "psr-12",
            Self::Pint => "pint",
            Self::Tempest => "tempest",
            Self::Hack => "hack",
            Self::Drupal => "drupal",
        }
    }

    pub const fn description(self) -> &'static str {
        match self {
            Self::Default => "Default preset (PER-CS compatible)",
            Self::Psr12 => "PSR-12 preset",
            Self::Pint => "Pint preset (Laravel Pint compatible)",
            Self::Tempest => "Tempest preset (Tempest framework compatible)",
            Self::Hack => "Hack preset (`hackfmt` compatible)",
            Self::Drupal => "Drupal preset",
        }
    }

    /// Returns all available presets.
    #[must_use]
    pub const fn all() -> &'static [FormatterPreset] {
        &[Self::Default, Self::Psr12, Self::Pint, Self::Tempest, Self::Hack, Self::Drupal]
    }
}

impl FromStr for FormatterPreset {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_lowercase().as_str() {
            "default" | "per-cs" | "percs" => Ok(Self::Default),
            "psr-12" | "psr12" => Ok(Self::Psr12),
            "pint" | "laravel-pint" | "laravel_pint" | "laravel" => Ok(Self::Pint),
            "tempest" | "tempest-php" | "tempest_php" => Ok(Self::Tempest),
            "hack" | "hackfmt" | "hhvm" => Ok(Self::Hack),
            "drupal" => Ok(Self::Drupal),
            _ => Err(format!(
                "unknown preset '{}', available presets: {}",
                s,
                Self::all().iter().map(|p| p.name()).collect::<Vec<_>>().join(", ")
            )),
        }
    }
}

impl fmt::Display for FormatterPreset {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.name())
    }
}

impl TryFrom<String> for FormatterPreset {
    type Error = String;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        Self::from_str(&value)
    }
}

/// The default formatter preset (PER-CS compatible).
const DEFAULT_PRESET: FormatSettings = FormatSettings {
    print_width: 120,
    tab_width: 4,
    use_tabs: false,
    end_of_line: EndOfLine::Auto,
    single_quote: true,
    trailing_comma: true,
    remove_trailing_close_tag: true,
    control_brace_style: BraceStyle::SameLine,
    following_clause_on_newline: false,
    closure_brace_style: BraceStyle::SameLine,
    function_brace_style: BraceStyle::NextLine,
    method_brace_style: BraceStyle::NextLine,
    classlike_brace_style: BraceStyle::AlwaysNextLine,
    inline_empty_control_braces: false,
    inline_empty_closure_braces: true,
    inline_empty_function_braces: false,
    inline_empty_method_braces: false,
    inline_empty_constructor_braces: true,
    inline_empty_classlike_braces: true,
    inline_empty_anonymous_class_braces: true,
    method_chain_breaking_style: MethodChainBreakingStyle::NextLine,
    first_method_chain_on_new_line: true,
    preserve_breaking_member_access_chain: false,
    preserve_breaking_argument_list: false,
    preserve_breaking_array_like: true,
    preserve_breaking_parameter_list: false,
    preserve_breaking_attribute_list: false,
    preserve_breaking_conditional_expression: false,
    break_promoted_properties_list: true,
    line_before_binary_operator: true,
    always_break_named_arguments_list: false,
    always_break_attribute_named_argument_lists: false,
    array_table_style_alignment: true,
    align_assignment_like: false,
    sort_uses: true,
    sort_class_methods: false,
    separate_use_types: true,
    expand_use_groups: true,
    null_type_hint: NullTypeHint::Question,
    parentheses_around_new_in_member_access: false,
    parentheses_in_new_expression: true,
    parentheses_in_exit_and_die: true,
    parentheses_in_attribute: false,
    space_before_arrow_function_parameter_list_parenthesis: false,
    space_before_closure_parameter_list_parenthesis: true,
    space_before_hook_parameter_list_parenthesis: false,
    inline_abstract_property_hooks: true,
    space_before_closure_use_clause_parenthesis: true,
    space_after_cast_unary_prefix_operators: true,
    space_after_reference_unary_prefix_operator: false,
    space_after_error_control_unary_prefix_operator: false,
    space_after_logical_not_unary_prefix_operator: false,
    space_after_bitwise_not_unary_prefix_operator: false,
    space_after_increment_unary_prefix_operator: false,
    space_after_decrement_unary_prefix_operator: false,
    space_after_additive_unary_prefix_operator: false,
    space_around_concatenation_binary_operator: true,
    space_around_assignment_in_declare: false,
    space_within_grouping_parenthesis: false,
    empty_line_after_control_structure: false,
    empty_line_after_opening_tag: true,
    empty_line_after_declare: true,
    empty_line_after_namespace: true,
    empty_line_after_use: true,
    empty_line_after_symbols: true,
    empty_line_between_same_symbols: true,
    empty_line_after_class_like_constant: false,
    empty_line_after_class_like_open: false,
    empty_line_before_class_like_close: false,
    empty_line_after_enum_case: false,
    empty_line_after_trait_use: false,
    empty_line_after_property: false,
    empty_line_after_method: true,
    empty_line_before_return: false,
    empty_line_before_dangling_comments: true,
    separate_class_like_members: true,
    indent_heredoc: true,
    uppercase_literal_keyword: false,
};

/// The PSR-12 formatter preset.
const PSR12_PRESET: FormatSettings = FormatSettings {
    print_width: 120,
    tab_width: 4,
    use_tabs: false,
    end_of_line: EndOfLine::Lf,
    single_quote: true,
    trailing_comma: false,
    remove_trailing_close_tag: true,
    control_brace_style: BraceStyle::SameLine,
    following_clause_on_newline: false,
    closure_brace_style: BraceStyle::SameLine,
    function_brace_style: BraceStyle::NextLine,
    method_brace_style: BraceStyle::NextLine,
    classlike_brace_style: BraceStyle::AlwaysNextLine,
    inline_empty_control_braces: false,
    inline_empty_closure_braces: true,
    inline_empty_function_braces: false,
    inline_empty_method_braces: false,
    inline_empty_constructor_braces: false,
    inline_empty_classlike_braces: false,
    inline_empty_anonymous_class_braces: true,
    method_chain_breaking_style: MethodChainBreakingStyle::NextLine,
    first_method_chain_on_new_line: true,
    preserve_breaking_member_access_chain: false,
    preserve_breaking_argument_list: false,
    preserve_breaking_array_like: true,
    preserve_breaking_parameter_list: true,
    preserve_breaking_attribute_list: false,
    preserve_breaking_conditional_expression: false,
    break_promoted_properties_list: true,
    line_before_binary_operator: true,
    always_break_named_arguments_list: false,
    always_break_attribute_named_argument_lists: false,
    array_table_style_alignment: true,
    align_assignment_like: false,
    sort_uses: false,
    sort_class_methods: false,
    separate_use_types: true,
    expand_use_groups: false,
    null_type_hint: NullTypeHint::Question,
    parentheses_around_new_in_member_access: false,
    parentheses_in_new_expression: true,
    parentheses_in_exit_and_die: true,
    parentheses_in_attribute: false,
    space_before_arrow_function_parameter_list_parenthesis: false,
    space_before_closure_parameter_list_parenthesis: true,
    space_before_hook_parameter_list_parenthesis: false,
    inline_abstract_property_hooks: true,
    space_before_closure_use_clause_parenthesis: true,
    space_after_cast_unary_prefix_operators: true,
    space_after_reference_unary_prefix_operator: false,
    space_after_error_control_unary_prefix_operator: false,
    space_after_logical_not_unary_prefix_operator: false,
    space_after_bitwise_not_unary_prefix_operator: false,
    space_after_increment_unary_prefix_operator: false,
    space_after_decrement_unary_prefix_operator: false,
    space_after_additive_unary_prefix_operator: false,
    space_around_concatenation_binary_operator: true,
    space_around_assignment_in_declare: true,
    space_within_grouping_parenthesis: true,
    empty_line_after_control_structure: false,
    empty_line_after_opening_tag: true,
    empty_line_after_declare: true,
    empty_line_after_namespace: true,
    empty_line_after_use: true,
    empty_line_after_symbols: true,
    empty_line_between_same_symbols: true,
    empty_line_after_class_like_constant: false,
    empty_line_after_class_like_open: false,
    empty_line_before_class_like_close: false,
    empty_line_after_enum_case: false,
    empty_line_after_trait_use: false,
    empty_line_after_property: false,
    empty_line_after_method: true,
    empty_line_before_return: false,
    empty_line_before_dangling_comments: true,
    separate_class_like_members: true,
    indent_heredoc: true,
    uppercase_literal_keyword: false,
};

/// The Pint formatter preset (Laravel Pint compatible).
const PINT_PRESET: FormatSettings = FormatSettings {
    print_width: 120,
    tab_width: 4,
    use_tabs: false,
    end_of_line: EndOfLine::Lf,
    single_quote: true,
    trailing_comma: true,
    remove_trailing_close_tag: true,
    control_brace_style: BraceStyle::SameLine,
    following_clause_on_newline: false,
    closure_brace_style: BraceStyle::SameLine,
    function_brace_style: BraceStyle::NextLine,
    method_brace_style: BraceStyle::NextLine,
    classlike_brace_style: BraceStyle::AlwaysNextLine,
    inline_empty_control_braces: false,
    inline_empty_closure_braces: false,
    inline_empty_function_braces: false,
    inline_empty_method_braces: false,
    inline_empty_constructor_braces: true,
    inline_empty_classlike_braces: true,
    inline_empty_anonymous_class_braces: false,
    method_chain_breaking_style: MethodChainBreakingStyle::NextLine,
    first_method_chain_on_new_line: false,
    preserve_breaking_member_access_chain: true,
    preserve_breaking_argument_list: true,
    preserve_breaking_array_like: true,
    preserve_breaking_parameter_list: true,
    preserve_breaking_attribute_list: true,
    preserve_breaking_conditional_expression: true,
    break_promoted_properties_list: true,
    line_before_binary_operator: true,
    always_break_named_arguments_list: false,
    always_break_attribute_named_argument_lists: false,
    array_table_style_alignment: true,
    align_assignment_like: false,
    sort_uses: true,
    sort_class_methods: false,
    separate_use_types: true,
    expand_use_groups: true,
    null_type_hint: NullTypeHint::Question,
    parentheses_around_new_in_member_access: false,
    parentheses_in_new_expression: false,
    parentheses_in_exit_and_die: true,
    parentheses_in_attribute: false,
    space_before_arrow_function_parameter_list_parenthesis: true,
    space_before_closure_parameter_list_parenthesis: true,
    space_before_hook_parameter_list_parenthesis: false,
    inline_abstract_property_hooks: true,
    space_before_closure_use_clause_parenthesis: true,
    space_after_cast_unary_prefix_operators: true,
    space_after_reference_unary_prefix_operator: false,
    space_after_error_control_unary_prefix_operator: false,
    space_after_logical_not_unary_prefix_operator: false,
    space_after_bitwise_not_unary_prefix_operator: false,
    space_after_increment_unary_prefix_operator: false,
    space_after_decrement_unary_prefix_operator: false,
    space_after_additive_unary_prefix_operator: false,
    space_around_concatenation_binary_operator: false,
    space_around_assignment_in_declare: true,
    space_within_grouping_parenthesis: true,
    empty_line_after_control_structure: false,
    empty_line_after_opening_tag: true,
    empty_line_after_declare: true,
    empty_line_after_namespace: true,
    empty_line_after_use: true,
    empty_line_after_symbols: true,
    empty_line_between_same_symbols: true,
    empty_line_after_class_like_constant: false,
    empty_line_after_class_like_open: false,
    empty_line_before_class_like_close: false,
    empty_line_after_enum_case: false,
    empty_line_after_trait_use: false,
    empty_line_after_property: false,
    empty_line_after_method: true,
    empty_line_before_return: true,
    empty_line_before_dangling_comments: true,
    separate_class_like_members: true,
    indent_heredoc: true,
    uppercase_literal_keyword: false,
};

/// The Tempest formatter preset (Tempest framework compatible).
const TEMPEST_PRESET: FormatSettings = FormatSettings {
    print_width: 180,
    tab_width: 4,
    use_tabs: false,
    end_of_line: EndOfLine::Auto,
    single_quote: true,
    trailing_comma: true,
    remove_trailing_close_tag: true,
    control_brace_style: BraceStyle::SameLine,
    following_clause_on_newline: false,
    closure_brace_style: BraceStyle::SameLine,
    function_brace_style: BraceStyle::NextLine,
    method_brace_style: BraceStyle::NextLine,
    classlike_brace_style: BraceStyle::AlwaysNextLine,
    inline_empty_control_braces: false,
    inline_empty_closure_braces: true,
    inline_empty_function_braces: false,
    inline_empty_method_braces: false,
    inline_empty_constructor_braces: true,
    inline_empty_classlike_braces: true,
    inline_empty_anonymous_class_braces: true,
    method_chain_breaking_style: MethodChainBreakingStyle::NextLine,
    first_method_chain_on_new_line: true,
    preserve_breaking_member_access_chain: true,
    preserve_breaking_argument_list: true,
    preserve_breaking_array_like: true,
    preserve_breaking_parameter_list: true,
    preserve_breaking_attribute_list: true,
    preserve_breaking_conditional_expression: true,
    break_promoted_properties_list: true,
    line_before_binary_operator: true,
    always_break_named_arguments_list: false,
    always_break_attribute_named_argument_lists: false,
    array_table_style_alignment: true,
    align_assignment_like: false,
    sort_uses: true,
    sort_class_methods: false,
    separate_use_types: true,
    expand_use_groups: true,
    null_type_hint: NullTypeHint::Question,
    parentheses_around_new_in_member_access: false,
    parentheses_in_new_expression: true,
    parentheses_in_exit_and_die: true,
    parentheses_in_attribute: false,
    space_before_arrow_function_parameter_list_parenthesis: true,
    space_before_closure_parameter_list_parenthesis: true,
    space_before_hook_parameter_list_parenthesis: false,
    inline_abstract_property_hooks: true,
    space_before_closure_use_clause_parenthesis: true,
    space_after_cast_unary_prefix_operators: true,
    space_after_reference_unary_prefix_operator: false,
    space_after_error_control_unary_prefix_operator: false,
    space_after_logical_not_unary_prefix_operator: true,
    space_after_bitwise_not_unary_prefix_operator: false,
    space_after_increment_unary_prefix_operator: false,
    space_after_decrement_unary_prefix_operator: false,
    space_after_additive_unary_prefix_operator: false,
    space_around_concatenation_binary_operator: true,
    space_around_assignment_in_declare: false,
    space_within_grouping_parenthesis: false,
    empty_line_after_control_structure: false,
    empty_line_after_opening_tag: false,
    empty_line_after_declare: true,
    empty_line_after_namespace: true,
    empty_line_after_use: true,
    empty_line_after_symbols: true,
    empty_line_between_same_symbols: true,
    empty_line_after_class_like_constant: false,
    empty_line_after_class_like_open: false,
    empty_line_before_class_like_close: false,
    empty_line_after_enum_case: false,
    empty_line_after_trait_use: false,
    empty_line_after_property: false,
    empty_line_after_method: true,
    empty_line_before_return: false,
    empty_line_before_dangling_comments: true,
    separate_class_like_members: true,
    indent_heredoc: false,
    uppercase_literal_keyword: false,
};

/// The Hack formatter preset (`hackfmt` compatible).
const HACK_PRESET: FormatSettings = FormatSettings {
    print_width: 80,
    tab_width: 2,
    use_tabs: false,
    end_of_line: EndOfLine::Lf,
    single_quote: true,
    trailing_comma: true,
    remove_trailing_close_tag: true,
    control_brace_style: BraceStyle::SameLine,
    following_clause_on_newline: false,
    closure_brace_style: BraceStyle::SameLine,
    function_brace_style: BraceStyle::SameLine,
    method_brace_style: BraceStyle::SameLine,
    classlike_brace_style: BraceStyle::SameLine,
    inline_empty_control_braces: true,
    inline_empty_closure_braces: true,
    inline_empty_function_braces: true,
    inline_empty_method_braces: true,
    inline_empty_constructor_braces: true,
    inline_empty_classlike_braces: true,
    inline_empty_anonymous_class_braces: true,
    method_chain_breaking_style: MethodChainBreakingStyle::NextLine,
    first_method_chain_on_new_line: false,
    preserve_breaking_member_access_chain: false,
    preserve_breaking_argument_list: false,
    preserve_breaking_array_like: false,
    preserve_breaking_parameter_list: false,
    preserve_breaking_attribute_list: false,
    preserve_breaking_conditional_expression: false,
    break_promoted_properties_list: true,
    line_before_binary_operator: true,
    always_break_named_arguments_list: true,
    always_break_attribute_named_argument_lists: true,
    array_table_style_alignment: true,
    align_assignment_like: false,
    sort_uses: true,
    sort_class_methods: false,
    separate_use_types: true,
    expand_use_groups: true,
    null_type_hint: NullTypeHint::Question,
    parentheses_around_new_in_member_access: true,
    parentheses_in_new_expression: true,
    parentheses_in_exit_and_die: true,
    parentheses_in_attribute: false,
    space_before_arrow_function_parameter_list_parenthesis: true,
    space_before_closure_parameter_list_parenthesis: true,
    space_before_hook_parameter_list_parenthesis: false,
    inline_abstract_property_hooks: true,
    space_before_closure_use_clause_parenthesis: true,
    space_after_cast_unary_prefix_operators: true,
    space_after_reference_unary_prefix_operator: false,
    space_after_error_control_unary_prefix_operator: false,
    space_after_logical_not_unary_prefix_operator: false,
    space_after_bitwise_not_unary_prefix_operator: false,
    space_after_increment_unary_prefix_operator: false,
    space_after_decrement_unary_prefix_operator: false,
    space_after_additive_unary_prefix_operator: false,
    space_around_concatenation_binary_operator: true,
    space_around_assignment_in_declare: false,
    space_within_grouping_parenthesis: false,
    empty_line_after_control_structure: false,
    empty_line_after_opening_tag: false,
    empty_line_after_declare: true,
    empty_line_after_namespace: true,
    empty_line_after_use: true,
    empty_line_after_symbols: true,
    empty_line_between_same_symbols: true,
    empty_line_after_class_like_constant: false,
    empty_line_after_class_like_open: false,
    empty_line_before_class_like_close: false,
    empty_line_after_enum_case: false,
    empty_line_after_trait_use: false,
    empty_line_after_property: false,
    empty_line_after_method: true,
    empty_line_before_return: true,
    empty_line_before_dangling_comments: true,
    separate_class_like_members: true,
    indent_heredoc: false,
    uppercase_literal_keyword: false,
};

/// The Drupal formatter preset.
const DRUPAL_PRESET: FormatSettings = FormatSettings {
    print_width: 120,
    tab_width: 2,
    use_tabs: false,
    end_of_line: EndOfLine::Lf,
    single_quote: true,
    trailing_comma: true,
    remove_trailing_close_tag: true,
    control_brace_style: BraceStyle::SameLine,
    following_clause_on_newline: true,
    closure_brace_style: BraceStyle::SameLine,
    function_brace_style: BraceStyle::SameLine,
    method_brace_style: BraceStyle::SameLine,
    classlike_brace_style: BraceStyle::SameLine,
    inline_empty_control_braces: false,
    inline_empty_closure_braces: true,
    inline_empty_function_braces: false,
    inline_empty_method_braces: false,
    inline_empty_constructor_braces: true,
    inline_empty_classlike_braces: true,
    inline_empty_anonymous_class_braces: true,
    method_chain_breaking_style: MethodChainBreakingStyle::NextLine,
    first_method_chain_on_new_line: true,
    preserve_breaking_member_access_chain: true,
    preserve_breaking_argument_list: true,
    preserve_breaking_array_like: true,
    preserve_breaking_parameter_list: true,
    preserve_breaking_attribute_list: true,
    preserve_breaking_conditional_expression: true,
    break_promoted_properties_list: true,
    line_before_binary_operator: true,
    always_break_named_arguments_list: false,
    always_break_attribute_named_argument_lists: false,
    array_table_style_alignment: false,
    align_assignment_like: false,
    sort_uses: true,
    sort_class_methods: false,
    separate_use_types: true,
    expand_use_groups: true,
    null_type_hint: NullTypeHint::Question,
    parentheses_around_new_in_member_access: false,
    parentheses_in_new_expression: true,
    parentheses_in_exit_and_die: true,
    parentheses_in_attribute: false,
    space_before_arrow_function_parameter_list_parenthesis: true,
    space_before_closure_parameter_list_parenthesis: true,
    space_before_hook_parameter_list_parenthesis: false,
    inline_abstract_property_hooks: true,
    space_before_closure_use_clause_parenthesis: true,
    space_after_cast_unary_prefix_operators: true,
    space_after_reference_unary_prefix_operator: false,
    space_after_error_control_unary_prefix_operator: false,
    space_after_logical_not_unary_prefix_operator: false,
    space_after_bitwise_not_unary_prefix_operator: false,
    space_after_increment_unary_prefix_operator: false,
    space_after_decrement_unary_prefix_operator: false,
    space_after_additive_unary_prefix_operator: false,
    space_around_concatenation_binary_operator: true,
    space_around_assignment_in_declare: false,
    space_within_grouping_parenthesis: false,
    empty_line_after_control_structure: false,
    empty_line_after_opening_tag: true,
    empty_line_after_declare: true,
    empty_line_after_namespace: true,
    empty_line_after_use: true,
    empty_line_after_symbols: true,
    empty_line_between_same_symbols: true,
    empty_line_after_class_like_constant: false,
    empty_line_after_class_like_open: true,
    empty_line_before_class_like_close: true,
    empty_line_after_enum_case: false,
    empty_line_after_trait_use: false,
    empty_line_after_property: false,
    empty_line_after_method: true,
    empty_line_before_return: false,
    empty_line_before_dangling_comments: true,
    separate_class_like_members: true,
    indent_heredoc: true,
    uppercase_literal_keyword: true,
};
